# Generated by Django 5.1.2 on 2024-10-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='house_no',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mobiles & Accessories', 'Mobiles & Accessories'), ('Vechicles', 'Vechicles'), ('Electronics & Appliances', 'Electronics & Appliances'), ('Furniture', 'Furniture'), ('Fashion', 'Fashion'), ('Books & Hobbies', 'Books & Hobbies'), ('Sports', 'Sports'), ('Pet Food & Accessories', 'Pet Food & Accessories')], max_length=50),
        ),
    ]
