# Generated by Django 5.1.2 on 2024-10-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_address_address_remove_address_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
