# Generated by Django 5.1.2 on 2024-10-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], default='Home', max_length=10),
        ),
    ]
