# Generated by Django 5.1.2 on 2024-10-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_address_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
