# Generated by Django 5.1.2 on 2024-10-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_address_user_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
