# Generated by Django 5.1.2 on 2024-10-22 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cash_on_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_on_delivery',
            name='product_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product'),
        ),
        migrations.AlterField(
            model_name='cash_on_delivery',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('de02207c-97dc-4321-8c5e-e445bfbfa67d'), null=True),
        ),
    ]
