# Generated by Django 5.1.2 on 2024-10-22 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cash_on_delivery_product_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_on_delivery',
            name='order_id',
            field=models.UUIDField(default=uuid.UUID('09fed703-cd74-4241-a0d8-9954dbdaa0f5'), null=True),
        ),
        migrations.RemoveField(
            model_name='cash_on_delivery',
            name='product_object',
        ),
        migrations.AddField(
            model_name='cash_on_delivery',
            name='product_object',
            field=models.ManyToManyField(null=True, to='cart.product'),
        ),
    ]
